source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EggMobilePushNotification_Example', :exclusive => true do
  pod "EggMobilePushNotification", :path => "../"
end

target 'EggMobilePushNotification_Tests', :exclusive => true do

end
